name: about_you
description: About You's Flutter Coding Challenge.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true