name: aratech
description: A new Flutter project.
version: 1.0.0+1

environment:
  flutter: ">=1.20.4 <2.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  firebase_crashlytics: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.5
  flutter_localizations:
    sdk: flutter
  http: ^0.12.2
  intl: ^0.16.1

dev_dependencies:
  bloc_test: ^7.0.4
  # flutter drive --profile --cache-sksl --write-sksl-on-exit shaders.sksl.json -t test_driver/main.dart
  # flutter build appbundle/ios --bundle-sksl-path shaders.sksl.json
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# Para generar localizaciones, ejecutar "flutter pub global run intl_utils:generate"
flutter_intl:
  enabled: true
  main_locale: es